
cygwin:
	make TOLUA=tolua++_cygwin.exe  -C libluascript
	make TOLUA=tolua++_cygwin.exe  -C libfaeris
	make TOLUA=tolua++_cygwin.exe  -C libspinesprite
	make TOLUA=tolua++_cygwin.exe  -C libbox2d
	make TOLUA=tolua++_cygwin.exe  -C libfaerisext

linux:
	make TOLUA=tolua++_linux.exe  -C libluascript
	make TOLUA=tolua++_linux.exe  -C libfaeris
	make TOLUA=tolua++_linux.exe  -C libspinesprite
	make TOLUA=tolua++_linux.exe  -C libbox2d
	make TOLUA=tolua++_linux.exe  -C libfaerisext


win32:
	make TOLUA=tolua++_win32.exe  -C libluascript
	make TOLUA=tolua++_win32.exe  -C libfaeris
	make TOLUA=tolua++_win32.exe  -C libspinesprite
	make TOLUA=tolua++_win32.exe  -C libbox2d 
	make TOLUA=tolua++_win32.exe  -C libfaerisext





