

linux:
	make TOLUA=tolua++_linux.exe  -C libluascript
	make TOLUA=tolua++_linux.exe  -C libfaeris
	make TOLUA=tolua++_linux.exe  -C libspinesprite
	make TOLUA=tolua++_linux.exe  -C libbox2d
	make TOLUA=tolua++_linux.exe  -C libsensor
	make TOLUA=tolua++_linux.exe  -C libpayment


win32:
	make TOLUA=tolua++_win32.exe  -C libluascript
	make TOLUA=tolua++_win32.exe  -C libfaeris
	make TOLUA=tolua++_win32.exe  -C libspinesprite
	make TOLUA=tolua++_win32.exe  -C libbox2d 
	make TOLUA=tolua++_win32.exe  -C libsensor
	make TOLUA=tolua++_win32.exe  -C libpayment





