main: mesh_parser  anim_parser


mesh_parser:
	g++ -o mesh_parser.exe mesh_parser.cc ../src/md5mesh_grammer.cc  ../src/md5mesh_scanner.cc ../src/libmd5model.cc  -I../src 

anim_parser:
	g++ -o anim_parser.exe anim_parser.cc ../src/md5anim_grammer.cc  ../src/md5anim_scanner.cc ../src/libmd5model.cc  -I../src 
