# Normal Information 
CC=gcc
FILE_EXT=c

FLAGS_DEBUG= -g -Wall -Werror 
FLAGS_RELEASE= -O3 

#Project info
PROJECT_PATH= ../../../library/linux/3rdparty
PROJECT=libjpeg

SRC_DIR= ../src/
INCLUDE_DIR= -I../include

#Source File 
SRC= jaricom.c \
	 jcapimin.c \
	 jcapistd.c \
	 jcarith.c \
	 jccoefct.c \
	 jccolor.c \
	 jcdctmgr.c \
	 jchuff.c \
	 jcinit.c \
	 jcmainct.c \
	 jcmarker.c \
	 jcmaster.c \
	 jcomapi.c \
	 jcparam.c \
	 jcprepct.c \
	 jcsample.c \
	 jctrans.c \
	 jdapimin.c \
	 jdapistd.c \
	 jdarith.c \
	 jdatadst.c \
	 jdatasrc.c \
	 jdcoefct.c \
	 jdcolor.c \
	 jddctmgr.c \
	 jdhuff.c \
	 jdinput.c \
	 jdmainct.c \
	 jdmarker.c \
	 jdmaster.c \
	 jdmerge.c \
	 jdpostct.c \
	 jdsample.c \
	 jdtrans.c \
	 jerror.c \
	 jfdctflt.c \
	 jfdctfst.c \
	 jfdctint.c \
	 jidctflt.c \
	 jidctfst.c \
	 jidctint.c \
	 jmemmgr.c \
	 jmemnobs.c \
	 jquant1.c \
	 jquant2.c \
	 jutils.c \


include  ../../../MK_BUILD_STATIC_LIB
