# Normal Information 
CC=gcc
FILE_EXT=cc

FLAGS_DEBUG= -g -Wall -Werror 
FLAGS_RELEASE= -O3 


#Project infor 
PROJECT_PATH= ../../../library/osx//3rdparty/
PROJECT=glslext
SRC_DIR=../src
INCLUDE_DIR= -I./include 

#Source File 
SRC=  glslext_grammer.cc \
	  glslext_parser.cc \
	  glslext_scanner.cc \


include  ../../../MK_BUILD_STATIC_LIB



