/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_faeris_payment_Fs_PaymentJni */

#ifndef _Included_com_faeris_payment_Fs_PaymentJni
#define _Included_com_faeris_payment_Fs_PaymentJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_faeris_payment_Fs_PaymentJni
 * Method:    billingFinish
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_faeris_payment_Fs_1PaymentJni_billingFinish
  (JNIEnv *, jclass, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
