# Normal Information 
CC=gcc
FILE_EXT=c

FLAGS_DEBUG= -g -Wall -Werror 
FLAGS_RELEASE= -O3 


#Project infor 
PROJECT_PATH= ../../../library/osx//3rdparty/
PROJECT=libtga
SRC_DIR=../src
INCLUDE_DIR= -I./include 

#Source File 
SRC=  tga.c \
	  tgaio.c \
	  tgaread.c \
	  tgawrite.c \


include  ../../../MK_BUILD_STATIC_LIB



