/* DO NOT EDIT THIS FILE - it is machine generated */

#include "com_faeris_libpaymm_Fs_libpayMMJni.h"
#include "FsPayMM.h"
#include "FsLuaEngine.h"
#include "FsGlobal.h"


/* Header for class com_faeris_libpaymm_Fs_libpayMMJni */
NS_FS_BEGIN


#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_faeris_libpaymm_Fs_libpayMMJni
 * Method:    onBillingFinish
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_faeris_libpaymm_Fs_1libpayMMJni_onBillingFinish
  (JNIEnv * env, jclass, jint status, jstring order_id) 
  {
	  const char* t_order_id=env->GetStringUTFChars(order_id,NULL);
	  PayMM::getInstance()->onBillingFinish(status,std::string(t_order_id));
	  env->ReleaseStringUTFChars(order_id,t_order_id);
  }

/*
 * Class:     com_faeris_libpaymm_Fs_libpayMMJni
 * Method:    onInitFinish
 * Signature: (I)V
 */

JNIEXPORT void JNICALL Java_com_faeris_libpaymm_Fs_1libpayMMJni_onInitFinish
  (JNIEnv *, jclass, jint status )
  {
	  PayMM::getInstance()->onInitFinish(status);
  }

/*
 * Class:     com_faeris_libpaymm_Fs_libpayMMJni
 * Method:    onMuduleInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_faeris_libpaymm_Fs_1libpayMMJni_onMuduleInit
  (JNIEnv *, jclass)
  {
	  Fs_PayMM_Moduel_Init();
  }

#ifdef __cplusplus
}
#endif


NS_FS_END

