# Normal Information 
CC=gcc
FILE_EXT=c

FLAGS_DEBUG= -g -Wall -Werror 
FLAGS_RELEASE= -O3 


#Project infor 
PROJECT_PATH= ../../../library/linux//3rdparty/
PROJECT=jsonc
SRC_DIR=../src
INCLUDE_DIR= -I./include 

#Source File 
SRC=  cJSON.c 


include  ../../../MK_BUILD_STATIC_LIB



